/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AngleSumRouteImport } from './routes/angle-sum'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ParallelogramRouteImport } from './routes/parallelogram'
import { Route as TrapeziumRouteImport } from './routes/trapezium'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AngleSumRoute = AngleSumRouteImport.update({
  id: '/angle-sum',
  path: '/angle-sum',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ParallelogramRoute = ParallelogramRouteImport.update({
  id: '/parallelogram',
  path: '/parallelogram',
  getParentRoute: () => rootRouteImport,
} as any)
const TrapeziumRoute = TrapeziumRouteImport.update({
  id: '/trapezium',
  path: '/trapezium',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/angle-sum': typeof AngleSumRoute
  '/conditions': typeof ConditionsRoute
  '/parallelogram': typeof ParallelogramRoute
  '/trapezium': typeof TrapeziumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/angle-sum': typeof AngleSumRoute
  '/conditions': typeof ConditionsRoute
  '/parallelogram': typeof ParallelogramRoute
  '/trapezium': typeof TrapeziumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/angle-sum': typeof AngleSumRoute
  '/conditions': typeof ConditionsRoute
  '/parallelogram': typeof ParallelogramRoute
  '/trapezium': typeof TrapeziumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/angle-sum'
    | '/conditions'
    | '/parallelogram'
    | '/trapezium'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/angle-sum'
    | '/conditions'
    | '/parallelogram'
    | '/trapezium'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/angle-sum'
    | '/conditions'
    | '/parallelogram'
    | '/trapezium'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AngleSumRoute: typeof AngleSumRoute
  ConditionsRoute: typeof ConditionsRoute
  ParallelogramRoute: typeof ParallelogramRoute
  TrapeziumRoute: typeof TrapeziumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angle-sum': {
      id: '/angle-sum'
      path: '/angle-sum'
      fullPath: '/angle-sum'
      preLoaderRoute: typeof AngleSumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallelogram': {
      id: '/parallelogram'
      path: '/parallelogram'
      fullPath: '/parallelogram'
      preLoaderRoute: typeof ParallelogramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trapezium': {
      id: '/trapezium'
      path: '/trapezium'
      fullPath: '/trapezium'
      preLoaderRoute: typeof TrapeziumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AngleSumRoute: AngleSumRoute,
  ConditionsRoute: ConditionsRoute,
  ParallelogramRoute: ParallelogramRoute,
  TrapeziumRoute: TrapeziumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
